language: php

addons:
  postgresql: "9.4"

services:
  - postgresql
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - ls -la ./vendor/bin
  - psql -c "CREATE USER easetest WITH PASSWORD 'easetest'" -U postgres
  - psql -c 'CREATE DATABASE easetest OWNER easetest;' -U postgres
  - mysql -u root -e 'create database easetest;'  
  - mysql -u root -e "GRANT ALL ON easetest.* TO 'easetest'@'localhost' IDENTIFIED BY 'easetest' ;"  
  
script:
  - mkdir -p build
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phinx migrate -e testing -c tests/phinx.yml
  - ./vendor/bin/phinx migrate -e development -c tests/phinx.yml
  - cd tests
  - ../vendor/bin/phpunit -c configuration.xml --bootstrap Bootstrap.php src
  - echo todo ../vendor/bin/phpcs src --standard=psr2 -sp

after_script:
  - echo todo ../vendor/bin/coveralls
  