language: php

addons:
  postgresql: "9.4"

services:
  - postgresql
  - mysql

php:
  - 5.6
  - 7.0

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - psql -c "CREATE USER easetest WITH PASSWORD 'easetest'" -U postgres
  - psql -c 'CREATE DATABASE easetest OWNER easetest;' -U postgres
  - mysql -e 'create database easetest;'  
  - mysql -e 'GRANT ALL ON easetest.* TO \'easetest\'@\'localhost\' IDENTIFIED BY \'easetest\' ;'  
  
script:
  - mkdir -p build/logs
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phinx migrate -e testing -c tests/phinx.yml
  - ./vendor/bin/phinx migrate -e development -c tests/phinx.yml
  - ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs --bootstrap tests/Bootstrap.php
  - ./vendor/bin/phpcs src --standard=psr2 -sp

after_script:
  - php vendor/bin/coveralls

