<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-20 at 14:41:37.
 */
class EaseLoggerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var EaseLogger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EaseLogger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers EaseLogger::singleton
     * @todo   Implement testSingleton().
     */
    public function testSingleton() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseLogger::setupLogFiles
     * @todo   Implement testSetupLogFiles().
     */
    public function testSetupLogFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseLogger::setStoreMessages
     * @todo   Implement testSetStoreMessages().
     */
    public function testSetStoreMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseLogger::resetStoredMessages
     * @todo   Implement testResetStoredMessages().
     */
    public function testResetStoredMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseLogger::getStoredMessages
     * @todo   Implement testGetStoredMessages().
     */
    public function testGetStoredMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseLogger::addToLog
     * @todo   Implement testAddToLog().
     */
    public function testAddToLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseLogger::renameLogFile
     * @todo   Implement testRenameLogFile().
     */
    public function testRenameLogFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseLogger::setRunType
     * @todo   Implement testSetRunType().
     */
    public function testSetRunType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseLogger::testDirectory
     * @todo   Implement testTestDirectory().
     */
    public function testTestDirectory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseLogger::error
     * @todo   Implement testError().
     */
    public function testError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseLogger::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseLogger::getLogStyle
     * @todo   Implement testGetLogStyle().
     */
    public function testGetLogStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
