<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-20 at 14:41:35.
 */
class EaseUserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var EaseUser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EaseUser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers EaseUser::getUserName
     * @todo   Implement testGetUserName().
     */
    public function testGetUserName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::getUserEmail
     * @todo   Implement testGetUserEmail().
     */
    public function testGetUserEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::draw
     * @todo   Implement testDraw().
     */
    public function testDraw() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::getIcon
     * @todo   Implement testGetIcon().
     */
    public function testGetIcon() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::tryToLogin
     * @todo   Implement testTryToLogin().
     */
    public function testTryToLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::isAccountEnabled
     * @todo   Implement testIsAccountEnabled().
     */
    public function testIsAccountEnabled() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::loginSuccess
     * @todo   Implement testLoginSuccess().
     */
    public function testLoginSuccess() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::loadSettings
     * @todo   Implement testLoadSettings().
     */
    public function testLoadSettings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::getSettings
     * @todo   Implement testGetSettings().
     */
    public function testGetSettings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::passwordValidation
     * @todo   Implement testPasswordValidation().
     */
    public function testPasswordValidation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::encryptPassword
     * @todo   Implement testEncryptPassword().
     */
    public function testEncryptPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::passwordChange
     * @todo   Implement testPasswordChange().
     */
    public function testPasswordChange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::passwordCrackCheck
     * @todo   Implement testPasswordCrackCheck().
     */
    public function testPasswordCrackCheck() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::setUserLevel
     * @todo   Implement testSetUserLevel().
     */
    public function testSetUserLevel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::getUserID
     * @todo   Implement testGetUserID().
     */
    public function testGetUserID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::getUserLogin
     * @todo   Implement testGetUserLogin().
     */
    public function testGetUserLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::getPermission
     * @todo   Implement testGetPermission().
     */
    public function testGetPermission() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::logout
     * @todo   Implement testLogout().
     */
    public function testLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::getSettingValue
     * @todo   Implement testGetSettingValue().
     */
    public function testGetSettingValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::setSettings
     * @todo   Implement testSetSettings().
     */
    public function testSetSettings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::setSettingValue
     * @todo   Implement testSetSettingValue().
     */
    public function testSetSettingValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::loadPermissions
     * @todo   Implement testLoadPermissions().
     */
    public function testLoadPermissions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::saveToMySQL
     * @todo   Implement testSaveToMySQL().
     */
    public function testSaveToMySQL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::loadFromMySQL
     * @todo   Implement testLoadFromMySQL().
     */
    public function testLoadFromMySQL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseUser::getGravatar
     * @todo   Implement testGetGravatar().
     */
    public function testGetGravatar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
