<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-20 at 14:41:38.
 */
class EaseJQueryRadiobuttonGroupTest extends PHPUnit_Framework_TestCase {

    /**
     * @var EaseJQueryRadiobuttonGroup
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EaseJQueryRadiobuttonGroup;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers EaseJQueryRadiobuttonGroup::addLabel
     * @todo   Implement testAddLabel().
     */
    public function testAddLabel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseJQueryRadiobuttonGroup::finalize
     * @todo   Implement testFinalize().
     */
    public function testFinalize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
