<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-20 at 14:41:29.
 */
class EasePageWizardTest extends PHPUnit_Framework_TestCase {

    /**
     * @var EasePageWizard
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EasePageWizard;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers EasePageWizard::setCurrentByID
     * @todo   Implement testSetCurrentByID().
     */
    public function testSetCurrentByID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::jumpToNextStep
     * @todo   Implement testJumpToNextStep().
     */
    public function testJumpToNextStep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::buttonToNextStep
     * @todo   Implement testButtonToNextStep().
     */
    public function testButtonToNextStep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::setRequestedStep
     * @todo   Implement testSetRequestedStep().
     */
    public function testSetRequestedStep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::addStep
     * @todo   Implement testAddStep().
     */
    public function testAddStep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::addSteps
     * @todo   Implement testAddSteps().
     */
    public function testAddSteps() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::addNavigation
     * @todo   Implement testAddNavigation().
     */
    public function testAddNavigation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::getNavigation
     * @todo   Implement testGetNavigation().
     */
    public function testGetNavigation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::getStepList
     * @todo   Implement testGetStepList().
     */
    public function testGetStepList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::addStepList
     * @todo   Implement testAddStepList().
     */
    public function testAddStepList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::setCurrentStepByName
     * @todo   Implement testSetCurrentStepByName().
     */
    public function testSetCurrentStepByName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::setCurrentStepByID
     * @todo   Implement testSetCurrentStepByID().
     */
    public function testSetCurrentStepByID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::getStepName
     * @todo   Implement testGetStepName().
     */
    public function testGetStepName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::getStepID
     * @todo   Implement testGetStepID().
     */
    public function testGetStepID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::getFirstStep
     * @todo   Implement testGetFirstStep().
     */
    public function testGetFirstStep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::getNextStepID
     * @todo   Implement testGetNextStepID().
     */
    public function testGetNextStepID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::forward
     * @todo   Implement testForward().
     */
    public function testForward() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::backward
     * @todo   Implement testBackward().
     */
    public function testBackward() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::getPrevStepID
     * @todo   Implement testGetPrevStepID().
     */
    public function testGetPrevStepID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePageWizard::getLastStep
     * @todo   Implement testGetLastStep().
     */
    public function testGetLastStep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
