<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-20 at 14:41:30.
 */
class EaseWebPageTest extends PHPUnit_Framework_TestCase {

    /**
     * @var EaseWebPage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EaseWebPage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers EaseWebPage::getjQueryUISkin
     * @todo   Implement testGetjQueryUISkin().
     */
    public function testGetjQueryUISkin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseWebPage::addItem
     * @todo   Implement testAddItem().
     */
    public function testAddItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseWebPage::includeJavaScript
     * @todo   Implement testIncludeJavaScript().
     */
    public function testIncludeJavaScript() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseWebPage::addJavaScript
     * @todo   Implement testAddJavaScript().
     */
    public function testAddJavaScript() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseWebPage::addToScriptsStack
     * @todo   Implement testAddToScriptsStack().
     */
    public function testAddToScriptsStack() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseWebPage::addCSS
     * @todo   Implement testAddCSS().
     */
    public function testAddCSS() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseWebPage::includeCss
     * @todo   Implement testIncludeCss().
     */
    public function testIncludeCss() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseWebPage::getStatusMessagesAsHtml
     * @todo   Implement testGetStatusMessagesAsHtml().
     */
    public function testGetStatusMessagesAsHtml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseWebPage::setSkin
     * @todo   Implement testSetSkin().
     */
    public function testSetSkin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseWebPage::draw
     * @todo   Implement testDraw().
     */
    public function testDraw() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseWebPage::finalizeRegistred
     * @todo   Implement testFinalizeRegistred().
     */
    public function testFinalizeRegistred() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseWebPage::setPageTitle
     * @todo   Implement testSetPageTitle().
     */
    public function testSetPageTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
