<?php

namespace Test\Ease\JQuery;
use Ease\JQuery\Dialog;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:32.
 */
class DialogTest extends UIPartTest
{

    /**
     * @var Dialog
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        $this->object = new Dialog('test', 'Test', 'Test ?');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() 
    {
        
    }

        public function testConstructor()
    {
        $classname = get_class($this->object);

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
            ->disableOriginalConstructor()
            ->getMockForAbstractClass();
        $mock->__construct('test', 'Test', 'Test ?');
    }

    /**
     * @covers Ease\JQuery\Dialog::onDocumentReady
     * @todo   Implement testOnDocumentReady().
     */
    public function testOnDocumentReady() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\Dialog::finalize
     * @todo   Implement testFinalize().
     */
    public function testFinalize() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
