<?php

namespace Test\Ease\JQuery;
use Ease\JQuery\LinkButton;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:26.
 */
class LinkButtonTest extends UIPartTest
{

    /**
     * @var LinkButton
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        $this->object = new LinkButton('http://v.s.cz/', 'Vitex Software');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() 
    {
        
    }

    /**
     * @covers Ease\JQuery\LinkButton::onDocumentReady
     * @todo   Implement testOnDocumentReady().
     */
    public function testOnDocumentReady() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\LinkButton::setTagID
     * @todo   Implement testSetTagID().
     */
    public function testSetTagID() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\LinkButton::getTagID
     * @todo   Implement testGetTagID().
     */
    public function testGetTagID() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
