<?php

namespace Test\Ease\JQuery;

use Ease\JQuery\Part;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:24.
 */
class PartTest extends \Test\Ease\PageTest
{
    /**
     * @var Part
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Part();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers Ease\JQuery\Part::setPartName
     */
    public function testSetPartName()
    {
        $this->object->setPartName('test');
        $this->assertEquals('test', $this->object->partName);
    }

    /**
     * @covers Ease\JQuery\Part::onDocumentReady
     */
    public function testOnDocumentReady()
    {
        $this->assertEmpty($this->object->onDocumentReady());
    }

    /**
     * @covers Ease\JQuery\Part::finalize
     */
    public function testFinalize()
    {
        $this->object->finalize();
    }

    /**
     * @covers Ease\JQuery\Part::jQueryze
     */
    public function testJQueryze()
    {
        \Ease\JQuery\Part::jQueryze();
    }

    /**
     * @covers Ease\JQuery\Part::setPartProperties
     */
    public function testSetPartProperties()
    {
        $this->object->setPartProperties(['property'=>'test']);
    }

    /**
     * @covers Ease\JQuery\Part::getPartPropertiesToString
     */
    public function testGetPartPropertiesToString()
    {
        $this->object->getPartPropertiesToString();
    }

    /**
     * @covers Ease\JQuery\Part::partPropertiesToString
     */
    public function testPartPropertiesToString()
    {
        $this->assertEquals('',  $this->object->partPropertiesToString([]));
        
    }
}
