<?php

namespace Test\Ease\JQuery;
use Ease\JQuery\Slider;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:25.
 */
class SliderTest extends UIPartTest
{

    /**
     * @var Slider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        $this->object = new Slider('Slider');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() 
    {
        
    }

    /**
     * @covers Ease\JQuery\Slider::setObjectName
     * @todo   Implement testSetObjectName().
     */
    public function testSetObjectName() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\Slider::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\Slider::setValues
     * @todo   Implement testSetValues().
     */
    public function testSetValues() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\Slider::getTagName
     * @todo   Implement testGetTagName().
     */
    public function testGetTagName() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\Slider::onDocumentReady
     * @todo   Implement testOnDocumentReady().
     */
    public function testOnDocumentReady() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\Slider::afterAdd
     * @todo   Implement testAfterAdd().
     */
    public function testAfterAdd() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\Slider::finalize
     * @todo   Implement testFinalize().
     */
    public function testFinalize() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
