<?php

namespace Test\Ease\JQuery;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:28.
 */
class SubmitButtonTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SubmitButton
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SubmitButton;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ease\JQuery\SubmitButton::onDocumentReady
     * @todo   Implement testOnDocumentReady().
     */
    public function testOnDocumentReady() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\SubmitButton::setTagClass
     * @todo   Implement testSetTagClass().
     */
    public function testSetTagClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\SubmitButton::setTagName
     * @todo   Implement testSetTagName().
     */
    public function testSetTagName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
