<?php

namespace Test\Ease\JQuery;
use Ease\JQuery\UITabs;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:31.
 */
class UITabsTest extends UIPartTest
{

    /**
     * @var UITabs
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        $this->object = new UITabs('tabs');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() 
    {
        
    }

    /**
     * @covers Ease\JQuery\UITabs::addTab
     * @todo   Implement testAddTab().
     */
    public function testAddTab() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\UITabs::addAjaxTab
     * @todo   Implement testAddAjaxTab().
     */
    public function testAddAjaxTab() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\JQuery\UITabs::finalize
     * @todo   Implement testFinalize().
     */
    public function testFinalize() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
