<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-14 at 23:03:12.
 */
class EaseDbMSSQLTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var EaseDbMSSQL
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EaseDbMSSQL;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EaseDbMSSQL::singleton
     * @todo   Implement testSingleton().
     */
    public function testSingleton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::connect
     * @todo   Implement testConnect().
     */
    public function testConnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::selectDB
     * @todo   Implement testSelectDB().
     */
    public function testSelectDB()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::makeReport
     * @todo   Implement testMakeReport().
     */
    public function testMakeReport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::exeQuery
     * @todo   Implement testExeQuery().
     */
    public function testExeQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::queryToArray
     * @todo   Implement testQueryToArray().
     */
    public function testQueryToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::getTableNumRows
     * @todo   Implement testGetTableNumRows().
     */
    public function testGetTableNumRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::describe
     * @todo   Implement testDescribe().
     */
    public function testDescribe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::prepCols
     * @todo   Implement testPrepCols().
     */
    public function testPrepCols()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::prepUpdate
     * @todo   Implement testPrepUpdate().
     */
    public function testPrepUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::prepSelect
     * @todo   Implement testPrepSelect().
     */
    public function testPrepSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::tableExist
     * @todo   Implement testTableExist().
     */
    public function testTableExist()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::createTable
     * @todo   Implement testCreateTable().
     */
    public function testCreateTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::sanitizeQuery
     * @todo   Implement testSanitizeQuery().
     */
    public function testSanitizeQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::listTables
     * @todo   Implement testListTables().
     */
    public function testListTables()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseDbMSSQL::close
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
