<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-19 at 00:19:03.
 */
class EaseHtmlPTagTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var EaseHtmlPTag
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EaseHtmlPTag;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}
