<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-20 at 14:41:49.
 */
class EaseJQueryPartTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var EaseJQueryPart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EaseJQueryPart;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EaseJQueryPart::setPartName
     * @todo   Implement testSetPartName().
     */
    public function testSetPartName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseJQueryPart::onDocumentReady
     * @todo   Implement testOnDocumentReady().
     */
    public function testOnDocumentReady()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseJQueryPart::finalize
     * @todo   Implement testFinalize().
     */
    public function testFinalize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseJQueryPart::jQueryze
     * @todo   Implement testJQueryze().
     */
    public function testJQueryze()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseJQueryPart::setPartProperties
     * @todo   Implement testSetPartProperties().
     */
    public function testSetPartProperties()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseJQueryPart::getPartPropertiesToString
     * @todo   Implement testGetPartPropertiesToString().
     */
    public function testGetPartPropertiesToString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseJQueryPart::is_assoc
     * @todo   Implement testIs_assoc().
     */
    public function testIs_assoc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseJQueryPart::partPropertiesToString
     * @todo   Implement testPartPropertiesToString().
     */
    public function testPartPropertiesToString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
