<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-26 at 22:28:13.
 */
class EasePageTest extends EaseContainerTest
{

    /**
     * @var Ease\Page
     */
    protected
        $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Ease\Page;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EasePage::singleton
     * @todo   Implement testSingleton().
     */
    public function testSingleton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::assignWebPage
     * @todo   Implement testAssignWebPage().
     */
    public function testAssignWebPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::addJavaScript
     * @todo   Implement testAddJavaScript().
     */
    public function testAddJavaScript()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::includeJavaScript
     * @todo   Implement testIncludeJavaScript().
     */
    public function testIncludeJavaScript()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::addCSS
     * @todo   Implement testAddCSS().
     */
    public function testAddCSS()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::includeCss
     * @todo   Implement testIncludeCss().
     */
    public function testIncludeCss()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::redirect
     * @todo   Implement testRedirect().
     */
    public function testRedirect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::getUri
     * @todo   Implement testGetUri().
     */
    public function testGetUri()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::phpSelf
     * @todo   Implement testPhpSelf().
     */
    public function testPhpSelf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::onlyForLogged
     * @todo   Implement testOnlyForLogged().
     */
    public function testOnlyForLogged()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::getRequestValues
     * @todo   Implement testGetRequestValues().
     */
    public function testGetRequestValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::isPosted
     * @todo   Implement testIsPosted().
     */
    public function testIsPosted()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::sanitizeAsType
     * @todo   Implement testSanitizeAsType().
     */
    public function testSanitizeAsType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::getRequestValue
     * @todo   Implement testGetRequestValue().
     */
    public function testGetRequestValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::getGetValue
     * @todo   Implement testGetGetValue().
     */
    public function testGetGetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::getPostValue
     * @todo   Implement testGetPostValue().
     */
    public function testGetPostValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::isFormPosted
     * @todo   Implement testIsFormPosted().
     */
    public function testIsFormPosted()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::keepRequestValue
     * @todo   Implement testKeepRequestValue().
     */
    public function testKeepRequestValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::keepRequestValues
     * @todo   Implement testKeepRequestValues().
     */
    public function testKeepRequestValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::unKeepRequestValue
     * @todo   Implement testUnKeepRequestValue().
     */
    public function testUnKeepRequestValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::unKeepRequestValues
     * @todo   Implement testUnKeepRequestValues().
     */
    public function testUnKeepRequestValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::getLinkParametersToKeep
     * @todo   Implement testGetLinkParametersToKeep().
     */
    public function testGetLinkParametersToKeep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::setupWebPage
     * @todo   Implement testSetupWebPage().
     */
    public function testSetupWebPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::setOutputFormat
     * @todo   Implement testSetOutputFormat().
     */
    public function testSetOutputFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::getOutputFormat
     * @todo   Implement testGetOutputFormat().
     */
    public function testGetOutputFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::takeStatusMessages
     * @todo   Implement testTakeStatusMessages().
     */
    public function testTakeStatusMessages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EasePage::arrayToUrlParams
     * @todo   Implement testArrayToUrlParams().
     */
    public function testArrayToUrlParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
