<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-14 at 23:03:11.
 */
class EaseDataGridTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var EaseDataGrid
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EaseDataGrid;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EaseDataGrid::populate
     * @todo   Implement testPopulate().
     */
    public function testPopulate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
