<?php

require_once 'EaseBrickTest.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-26 at 22:25:35.
 */
class EaseContainerTest extends EaseSandTest
{

    /**
     * @var EaseContainer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EaseContainer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EaseContainer::raise
     * @todo   Implement testRaise().
     */
    public function testRaise()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::addItemCustom
     * @todo   Implement testAddItemCustom().
     */
    public function testAddItemCustom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::addItem
     * @todo   Implement testAddItem().
     */
    public function testAddItem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::addAsFirst
     * @todo   Implement testAddAsFirst().
     */
    public function testAddAsFirst()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::suicide
     * @todo   Implement testSuicide().
     */
    public function testSuicide()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::getItemsCount
     * @todo   Implement testGetItemsCount().
     */
    public function testGetItemsCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::addNextTo
     * @todo   Implement testAddNextTo().
     */
    public function testAddNextTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::lastItem
     * @todo   Implement testLastItem().
     */
    public function testLastItem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::addToLastItem
     * @todo   Implement testAddToLastItem().
     */
    public function testAddToLastItem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::getFirstPart
     * @todo   Implement testGetFirstPart().
     */
    public function testGetFirstPart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::addItems
     * @todo   Implement testAddItems().
     */
    public function testAddItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::emptyContents
     * @todo   Implement testEmptyContents().
     */
    public function testEmptyContents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::takeJavascripts
     * @todo   Implement testTakeJavascripts().
     */
    public function testTakeJavascripts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::takeCascadeStyles
     * @todo   Implement testTakeCascadeStyles().
     */
    public function testTakeCascadeStyles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::drawAllContents
     * @todo   Implement testDrawAllContents().
     */
    public function testDrawAllContents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::getRendered
     * @todo   Implement testGetRendered().
     */
    public function testGetRendered()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::showContents
     * @todo   Implement testShowContents().
     */
    public function testShowContents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::drawIfNotDrawn
     * @todo   Implement testDrawIfNotDrawn().
     */
    public function testDrawIfNotDrawn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::isFinalized
     * @todo   Implement testIsFinalized().
     */
    public function testIsFinalized()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::setFinalized
     * @todo   Implement testSetFinalized().
     */
    public function testSetFinalized()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::fillUp
     * @todo   Implement testFillUp().
     */
    public function testFillUp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::fillMeUp
     * @todo   Implement testFillMeUp().
     */
    public function testFillMeUp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::isEmpty
     * @todo   Implement testIsEmpty().
     */
    public function testIsEmpty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::draw
     * @todo   Implement testDraw().
     */
    public function testDraw()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseContainer::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
