<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-19 at 00:19:03.
 */
class EaseHtmlTagTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var EaseHtmlTag
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EaseHtmlTag;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EaseHtmlTag::setObjectName
     * @todo   Implement testSetObjectName().
     */
    public function testSetObjectName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::setTagName
     * @todo   Implement testSetTagName().
     */
    public function testSetTagName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::getTagName
     * @todo   Implement testGetTagName().
     */
    public function testGetTagName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::setTagType
     * @todo   Implement testSetTagType().
     */
    public function testSetTagType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::getTagType
     * @todo   Implement testGetTagType().
     */
    public function testGetTagType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::setTagClass
     * @todo   Implement testSetTagClass().
     */
    public function testSetTagClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::addTagClass
     * @todo   Implement testAddTagClass().
     */
    public function testAddTagClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::getTagClass
     * @todo   Implement testGetTagClass().
     */
    public function testGetTagClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::setTagID
     * @todo   Implement testSetTagID().
     */
    public function testSetTagID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::getTagID
     * @todo   Implement testGetTagID().
     */
    public function testGetTagID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::getTagProperty
     * @todo   Implement testGetTagProperty().
     */
    public function testGetTagProperty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::setTagProperties
     * @todo   Implement testSetTagProperties().
     */
    public function testSetTagProperties()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::tagPropertiesToString
     * @todo   Implement testTagPropertiesToString().
     */
    public function testTagPropertiesToString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::setTagCss
     * @todo   Implement testSetTagCss().
     */
    public function testSetTagCss()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::cssPropertiesToString
     * @todo   Implement testCssPropertiesToString().
     */
    public function testCssPropertiesToString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EaseHtmlTag::draw
     * @todo   Implement testDraw().
     */
    public function testDraw()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
