<?php

namespace Test\Ease\Html;

use Ease\Html\BodyTag;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:52.
 */
class BodyTagTest extends PairTagTest
{
    /**
     * @var BodyTag
     */
    protected $object;
    public $rendered = '<body></body>';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Html\BodyTag();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    public function testConstructor()
    {
        parent::testConstructor();
        $tester = new BodyTag('test');
        $this->assertEquals('test', $tester->getTagID());
    }

    /**
     * @covers Ease\Html\BodyTag::setObjectName
     */
    public function testSetObjectName()
    {
        $this->object->setObjectName();
        $this->assertEquals('body', $this->object->getObjectName());
    }
}
