<?php

namespace Test\Ease\Html;
use Ease\Html\BodyTag;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:52.
 */
class BodyTagTest extends PairTagTest
{

    /**
     * @var BodyTag
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        $this->object = new \Ease\Html\BodyTag;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() 
    {
        
    }

    /**
     * @covers Ease\Html\BodyTag::setObjectName
     * @todo   Implement testSetObjectName().
     */
    public function testSetObjectName() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
