<?php

namespace Test\Ease\Html;

use Ease\Html\CheckboxTag;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:06.
 */
class CheckboxTagTest extends InputTagTest
{
    /**
     * @var CheckboxTag
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Ease\Html\CheckboxTag('test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ease\Html\CheckboxTag::draw
     */
    public function testDraw($whatWant = null)
    {
        parent::testDraw('
<input type="checkbox" name="test" />');
    }

    /**
     * @covers Ease\Html\CheckboxTag::getTagName
     */
    public function testGetTagName()
    {
        $this->assertEquals('test', $this->object->getTagName());
        $this->object->setName = true;
        $this->object->setTagName('Test');
        $this->assertEquals('Test', $this->object->getTagName());
    }

    /**
     * @covers Ease\Html\CheckboxTag::setValue
     *
     * @todo   Implement testSetValue().
     */
    public function testSetValue()
    {
        $this->object->setValue(true);
        $this->assertEquals('true', $this->object->getTagProperty('checked'));
    }
}
