<?php

namespace Test\Ease\Html;

use Ease\Html\HeadTag;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:44.
 */
class HeadTagTest extends PairTagTest
{
    /**
     * @var HeadTag
     */
    protected $object;
    public $rendered = '<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new HeadTag();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers Ease\Html\HeadTag::setObjectName
     *
     * @todo   Implement testSetObjectName().
     */
    public function testSetObjectName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Html\HeadTag::jsEnclosure
     *
     * @todo   Implement testJsEnclosure().
     */
    public function testJsEnclosure()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Html\HeadTag::finalize
     *
     * @todo   Implement testFinalize().
     */
    public function testFinalize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Html\HeadTag::draw
     */
    public function testDraw($whatWant = null)
    {
        parent::testDraw($this->rendered);
    }
}
