<?php

namespace Test\Ease\Html;

use Ease\Html\HtmlTag;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:54.
 */
class HtmlTagTest extends PairTagTest
{
    /**
     * @var HtmlTag
     */
    protected $object;
    public $rendered = '<html lang="cs-CZ"></html>';
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Html\HtmlTag();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers Ease\Html\HtmlTag::setObjectName
     *
     * @todo   Implement testSetObjectName().
     */
    public function testSetObjectName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
