<?php

namespace Test\Ease\Html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:43.
 */
class IframeTagTest extends PairTagTest
{
    /**
     * @var IframeTag
     */
    protected $object;
    public $rendered = '<iframe src="http://v.s.cz/"></iframe>';
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Html\IframeTag('http://v.s.cz/');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }
}
