<?php

namespace Test\Ease\Html;

use Ease\Html\InputRadioTag;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:56.
 */
class InputRadioTagTest extends InputTagTest
{
    /**
     * @var InputRadioTag
     */
    protected $object;
    public $rendered = '<input name="radio" type="radio" />';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Html\InputRadioTag('radio');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers Ease\Html\InputRadioTag::setValue
     *
     * @todo   Implement testSetValue().
     */
    public function testSetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Html\InputRadioTag::getTagName
     */
    public function testGetTagName()
    {
        $this->assertEquals('radio', $this->object->getTagName());
        $this->object->setName = true;
        $this->object->setTagName('Test');
        $this->assertEquals('Test', $this->object->getTagName());
    }

    /**
     * 
     * @covers Ease\Html\InputRadioTag::draw
     */
    public function testDraw($whatWant = null)
    {
        parent::testDraw($this->rendered);
    }
    
    }
