<?php

namespace Test\Ease\Html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:45.
 */
class ScriptTagTest extends PairTagTest
{
    /**
     * @var ScriptTag
     */
    protected $object;
    public $rendered = '<script>// <![CDATA[

// ]]></script>';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Html\ScriptTag();
    }

 
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

}
