<?php

namespace Test\Ease\Html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:12.
 */
class SimpleHeadTagTest extends PairTagTest
{
    /**
     * @var SimpleHeadTag
     */
    protected $object;
    public $rendered = '<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Html\SimpleHeadTag();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }


}
