<?php

namespace Test\Ease\Html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:08.
 */
class SubmitButtonTest extends InputTagTest
{
    /**
     * @var SubmitButton
     */
    protected $object;
    public $rendered = '<input type="submit" name="test" value="test" />';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Html\SubmitButton('test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    public function testConstructor()
    {
        $classname = get_class($this->object);

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
            ->disableOriginalConstructor()
            ->getMockForAbstractClass();
        $mock->__construct('Test');

        $mock->__construct('option', 'value');
    }

    /**
     * 
     * @covers Ease\Html\SubmitButton::draw
     */
    public function testDraw($whatWant = null)
    {
         parent::testDraw($this->rendered);
    }

        /**
     * @covers Ease\Html\SubmitButton::setValue
     */
    public function testSetValue()
    {
        $this->object->setValue('tested');
        $this->assertEquals('', $this->object->draw());
    }
}
