<?php

namespace Test\Ease\Html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:10.
 */
class UlTagTest extends PairTagTest
{
    /**
     * @var UlTag
     */
    protected $object;
    public $rendered = '<ul>http://v.s.cz/</ul>';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Html\UlTag('http://v.s.cz/');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers Ease\Html\UlTag::addItems
     *
     * @todo   Implement testAddItems().
     */
    public function testAddItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Html\UlTag::addItemSmart
     *
     * @todo   Implement testAddItemSmart().
     */
    public function testAddItemSmart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
