<?php

namespace Ease;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:38.
 */
class AnonymTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Anonym
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Anonym;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ease\Anonym::setObjectName
     * @todo   Implement testSetObjectName().
     */
    public function testSetObjectName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Anonym::getUserLevel
     * @todo   Implement testGetUserLevel().
     */
    public function testGetUserLevel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Anonym::getUserID
     * @todo   Implement testGetUserID().
     */
    public function testGetUserID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Anonym::getUserLogin
     * @todo   Implement testGetUserLogin().
     */
    public function testGetUserLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Anonym::isLogged
     * @todo   Implement testIsLogged().
     */
    public function testIsLogged() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Anonym::getSettingValue
     * @todo   Implement testGetSettingValue().
     */
    public function testGetSettingValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Anonym::getUserEmail
     * @todo   Implement testGetUserEmail().
     */
    public function testGetUserEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Anonym::getPermission
     * @todo   Implement testGetPermission().
     */
    public function testGetPermission() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Anonym::logout
     * @todo   Implement testLogout().
     */
    public function testLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
