<?php

namespace Test\Ease;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:10.
 */
class DataGridTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var DataGrid
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        $this->object = new DataGrid;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() 
    {
        
    }

    /**
     * @covers Ease\DataGrid::populate
     * @todo   Implement testPopulate().
     */
    public function testPopulate() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
