<?php

namespace Test\Ease;

use Ease\Locale;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-06-27 at 13:23:52.
 */
class LocaleTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Locale
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Locale();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Ease\Locale::initializeGetText
     */
    public function testInitializeGetText()
    {
        Locale::initializeGetText('EaseTest', 'en_US', '../i18n');
    }
}
