<?php

namespace Test\Ease;

use Ease\LoggerToMemory;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:52.
 */
class LoggerToMemoryTest extends AtomTest
{
    /**
     * @var Logger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LoggerToMemory();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ease\LoggerToMemory::singleton
     *
     * @todo   Implement testSingleton().
     */
    public function testSingleton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToMemory::setStoreMessages
     *
     * @todo   Implement testSetStoreMessages().
     */
    public function testSetStoreMessages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToMemory::resetStoredMessages
     *
     * @todo   Implement testResetStoredMessages().
     */
    public function testResetStoredMessages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToMemory::getStoredMessages
     *
     * @todo   Implement testGetStoredMessages().
     */
    public function testGetStoredMessages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToMemory::addToLog
     *
     * @todo   Implement testAddToLog().
     */
    public function testAddToLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToMemory::error
     *
     * @todo   Implement testError().
     */
    public function testError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToMemory::getLogStyle
     *
     * @todo   Implement testGetLogStyle().
     */
    public function testGetLogStyle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
