<?php

namespace Test\Ease;

use Ease\LoggerToFile;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:52.
 */
class LoggerToFileTest extends AtomTest
{
    /**
     * @var Logger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LoggerToFile();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ease\LoggerToFile::singleton
     *
     * @todo   Implement testSingleton().
     */
    public function testSingleton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToFile::setupLogFiles
     *
     * @todo   Implement testSetupLogFiles().
     */
    public function testSetupLogFiles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToFile::setStoreMessages
     *
     * @todo   Implement testSetStoreMessages().
     */
    public function testSetStoreMessages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToFile::resetStoredMessages
     *
     * @todo   Implement testResetStoredMessages().
     */
    public function testResetStoredMessages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToFile::getStoredMessages
     *
     * @todo   Implement testGetStoredMessages().
     */
    public function testGetStoredMessages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToFile::addToLog
     *
     * @todo   Implement testAddToLog().
     */
    public function testAddToLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToFile::renameLogFile
     *
     * @todo   Implement testRenameLogFile().
     */
    public function testRenameLogFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToFile::setRunType
     *
     * @todo   Implement testSetRunType().
     */
    public function testSetRunType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToFile::testDirectory
     *
     * @todo   Implement testTestDirectory().
     */
    public function testTestDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToFile::error
     *
     * @todo   Implement testError().
     */
    public function testError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToFile::__destruct
     *
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\LoggerToFile::getLogStyle
     *
     * @todo   Implement testGetLogStyle().
     */
    public function testGetLogStyle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
