<?php

namespace Test\Ease;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:37.
 */
class PageTest extends ContainerTest
{

    /**
     * @var Page
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Page;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Ease\Page::singleton
     * @todo   Implement testSingleton().
     */
    public function testSingleton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::assignWebPage
     * @todo   Implement testAssignWebPage().
     */
    public function testAssignWebPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::addJavaScript
     * @todo   Implement testAddJavaScript().
     */
    public function testAddJavaScript()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::includeJavaScript
     * @todo   Implement testIncludeJavaScript().
     */
    public function testIncludeJavaScript()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::addCSS
     * @todo   Implement testAddCSS().
     */
    public function testAddCSS()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::includeCss
     * @todo   Implement testIncludeCss().
     */
    public function testIncludeCss()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::redirect
     * @todo   Implement testRedirect().
     */
    public function testRedirect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::getUri
     * @todo   Implement testGetUri().
     */
    public function testGetUri()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::phpSelf
     * @todo   Implement testPhpSelf().
     */
    public function testPhpSelf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::onlyForLogged
     * @todo   Implement testOnlyForLogged().
     */
    public function testOnlyForLogged()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::getRequestValues
     * @todo   Implement testGetRequestValues().
     */
    public function testGetRequestValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::isPosted
     * @todo   Implement testIsPosted().
     */
    public function testIsPosted()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::sanitizeAsType
     * @todo   Implement testSanitizeAsType().
     */
    public function testSanitizeAsType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::getRequestValue
     * @todo   Implement testGetRequestValue().
     */
    public function testGetRequestValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::getGetValue
     * @todo   Implement testGetGetValue().
     */
    public function testGetGetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::getPostValue
     * @todo   Implement testGetPostValue().
     */
    public function testGetPostValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::isFormPosted
     * @todo   Implement testIsFormPosted().
     */
    public function testIsFormPosted()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::keepRequestValue
     * @todo   Implement testKeepRequestValue().
     */
    public function testKeepRequestValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::keepRequestValues
     * @todo   Implement testKeepRequestValues().
     */
    public function testKeepRequestValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::unKeepRequestValue
     * @todo   Implement testUnKeepRequestValue().
     */
    public function testUnKeepRequestValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::unKeepRequestValues
     * @todo   Implement testUnKeepRequestValues().
     */
    public function testUnKeepRequestValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::getLinkParametersToKeep
     * @todo   Implement testGetLinkParametersToKeep().
     */
    public function testGetLinkParametersToKeep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::setupWebPage
     * @todo   Implement testSetupWebPage().
     */
    public function testSetupWebPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::setOutputFormat
     * @todo   Implement testSetOutputFormat().
     */
    public function testSetOutputFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::getOutputFormat
     * @todo   Implement testGetOutputFormat().
     */
    public function testGetOutputFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::takeStatusMessages
     * @todo   Implement testTakeStatusMessages().
     */
    public function testTakeStatusMessages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Page::arrayToUrlParams
     * @todo   Implement testArrayToUrlParams().
     */
    public function testArrayToUrlParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
