<?php

namespace Test\Ease;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:38.
 */
class PageWizardTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PageWizard
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PageWizard;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Ease\PageWizard::setCurrentByID
     * @todo   Implement testSetCurrentByID().
     */
    public function testSetCurrentByID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::jumpToNextStep
     * @todo   Implement testJumpToNextStep().
     */
    public function testJumpToNextStep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::buttonToNextStep
     * @todo   Implement testButtonToNextStep().
     */
    public function testButtonToNextStep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::setRequestedStep
     * @todo   Implement testSetRequestedStep().
     */
    public function testSetRequestedStep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::addStep
     * @todo   Implement testAddStep().
     */
    public function testAddStep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::addSteps
     * @todo   Implement testAddSteps().
     */
    public function testAddSteps()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::addNavigation
     * @todo   Implement testAddNavigation().
     */
    public function testAddNavigation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::getNavigation
     * @todo   Implement testGetNavigation().
     */
    public function testGetNavigation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::getStepList
     * @todo   Implement testGetStepList().
     */
    public function testGetStepList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::addStepList
     * @todo   Implement testAddStepList().
     */
    public function testAddStepList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::setCurrentStepByName
     * @todo   Implement testSetCurrentStepByName().
     */
    public function testSetCurrentStepByName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::setCurrentStepByID
     * @todo   Implement testSetCurrentStepByID().
     */
    public function testSetCurrentStepByID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::getStepName
     * @todo   Implement testGetStepName().
     */
    public function testGetStepName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::getStepID
     * @todo   Implement testGetStepID().
     */
    public function testGetStepID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::getFirstStep
     * @todo   Implement testGetFirstStep().
     */
    public function testGetFirstStep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::getNextStepID
     * @todo   Implement testGetNextStepID().
     */
    public function testGetNextStepID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::forward
     * @todo   Implement testForward().
     */
    public function testForward()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::backward
     * @todo   Implement testBackward().
     */
    public function testBackward()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::getPrevStepID
     * @todo   Implement testGetPrevStepID().
     */
    public function testGetPrevStepID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\PageWizard::getLastStep
     * @todo   Implement testGetLastStep().
     */
    public function testGetLastStep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
