<?php

namespace Test\Ease;

use Ease\Saver;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:35.
 */
class SaverTest extends BrickTest
{

    /**
     * @var Saver
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Saver;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Ease\Saver::createmyTable
     * @todo   Implement testCreatemyTable().
     */
    public function testCreatemyTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Saver::setUpUser
     * @todo   Implement testSetUpUser().
     */
    public function testSetUpUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Saver::insertToMySQL
     * @todo   Implement testInsertToMySQL().
     */
    public function testInsertToMySQL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Saver::createMissingColumns
     * @todo   Implement testCreateMissingColumns().
     */
    public function testCreateMissingColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Saver::loadFromMySQL
     * @todo   Implement testLoadFromMySQL().
     */
    public function testLoadFromMySQL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Saver::updateToMySQL
     * @todo   Implement testUpdateToMySQL().
     */
    public function testUpdateToMySQL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Saver::visualResponse
     * @todo   Implement testVisualResponse().
     */
    public function testVisualResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
