<?php

namespace Ease;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:23.
 */
class SysLoggerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SysLogger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SysLogger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ease\SysLogger::singleton
     * @todo   Implement testSingleton().
     */
    public function testSingleton() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SysLogger::setStoreMessages
     * @todo   Implement testSetStoreMessages().
     */
    public function testSetStoreMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SysLogger::resetStoredMessages
     * @todo   Implement testResetStoredMessages().
     */
    public function testResetStoredMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SysLogger::getStoredMessages
     * @todo   Implement testGetStoredMessages().
     */
    public function testGetStoredMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SysLogger::addToLog
     * @todo   Implement testAddToLog().
     */
    public function testAddToLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SysLogger::error
     * @todo   Implement testError().
     */
    public function testError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SysLogger::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SysLogger::getLogStyle
     * @todo   Implement testGetLogStyle().
     */
    public function testGetLogStyle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
