<?php

namespace Test\Ease;

use Ease\User;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:22.
 */
class UserTest extends AnonymTest
{
    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new User();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers Ease\User::getUserName
     *
     * @todo   Implement testGetUserName().
     */
    public function testGetUserName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::getUserEmail
     *
     * @todo   Implement testGetUserEmail().
     */
    public function testGetUserEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::draw
     *
     * @todo   Implement testDraw().
     */
    public function testDraw($whatWant = null)
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::getIcon
     *
     * @todo   Implement testGetIcon().
     */
    public function testGetIcon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::tryToLogin
     *
     * @todo   Implement testTryToLogin().
     */
    public function testTryToLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::isAccountEnabled
     *
     * @todo   Implement testIsAccountEnabled().
     */
    public function testIsAccountEnabled()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::loginSuccess
     *
     * @todo   Implement testLoginSuccess().
     */
    public function testLoginSuccess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::loadSettings
     *
     * @todo   Implement testLoadSettings().
     */
    public function testLoadSettings()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::saveSettings
     *
     * @todo   Implement testSaveSettings().
     */
    public function testSaveSettings()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::getSettings
     *
     * @todo   Implement testGetSettings().
     */
    public function testGetSettings()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::passwordValidation
     *
     * @todo   Implement testPasswordValidation().
     */
    public function testPasswordValidation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::encryptPassword
     *
     * @todo   Implement testEncryptPassword().
     */
    public function testEncryptPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::passwordChange
     *
     * @todo   Implement testPasswordChange().
     */
    public function testPasswordChange()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::getUserID
     *
     * @todo   Implement testGetUserID().
     */
    public function testGetUserID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::getUserLogin
     *
     * @todo   Implement testGetUserLogin().
     */
    public function testGetUserLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::setUserLogin
     *
     * @todo   Implement testSetUserLogin().
     */
    public function testSetUserLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::getPermission
     *
     * @todo   Implement testGetPermission().
     */
    public function testGetPermission()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::logout
     *
     * @todo   Implement testLogout().
     */
    public function testLogout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::getSettingValue
     *
     * @todo   Implement testGetSettingValue().
     */
    public function testGetSettingValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::setSettings
     *
     * @todo   Implement testSetSettings().
     */
    public function testSetSettings()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::setSettingValue
     *
     * @todo   Implement testSetSettingValue().
     */
    public function testSetSettingValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::loadPermissions
     *
     * @todo   Implement testLoadPermissions().
     */
    public function testLoadPermissions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::getName
     *
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::saveToSQL
     *
     * @todo   Implement testSaveToSQL().
     */
    public function testSaveToSQL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::loadFromSQL
     *
     * @todo   Implement testLoadFromSQL().
     */
    public function testLoadFromSQL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::getGravatar
     *
     * @todo   Implement testGetGravatar().
     */
    public function testGetGravatar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\User::setObjectName
     *
     * @todo   Implement testSetObjectName().
     */
    public function testSetObjectName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
