<?php

namespace Test\Ease\Logger;

use \Ease\Logger\ToStd;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-04-06 at 23:38:43.
 */
class ToStdTest extends ToMemoryTest
{
    /**
     * @var ToStd
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ToStd;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers Ease\Logger\ToStd::singleton
     * @todo   Implement testSingleton().
     */
    public function testSingleton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Logger\ToStd::addToLog
     * @todo   Implement testAddToLog().
     */
    public function testAddToLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Logger\ToStd::output
     * @todo   Implement testOutput().
     */
    public function testOutput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Logger\ToStd::error
     * @todo   Implement testError().
     */
    public function testError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Logger\ToStd::finalizeMessage
     * @todo   Implement testFinalizeMessage().
     */
    public function testFinalizeMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Logger\ToStd::flush
     * @todo   Implement testFlush().
     */
    public function testFlush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
