<?php

namespace Test\Ease\SQL;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:16.
 */
class MySqliTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var MySqli
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MySqli;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ease\SQL\MySqli::singleton
     * @todo   Implement testSingleton().
     */
    public function testSingleton() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::addSlashes
     * @todo   Implement testAddSlashes().
     */
    public function testAddSlashes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::connect
     * @todo   Implement testConnect().
     */
    public function testConnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::selectDB
     * @todo   Implement testSelectDB().
     */
    public function testSelectDB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::exeQuery
     * @todo   Implement testExeQuery().
     */
    public function testExeQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::queryToArray
     * @todo   Implement testQueryToArray().
     */
    public function testQueryToArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::arrayToInsert
     * @todo   Implement testArrayToInsert().
     */
    public function testArrayToInsert() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::arrayToUpdate
     * @todo   Implement testArrayToUpdate().
     */
    public function testArrayToUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::arrayToQuery
     * @todo   Implement testArrayToQuery().
     */
    public function testArrayToQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::prepSelect
     * @todo   Implement testPrepSelect().
     */
    public function testPrepSelect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::describe
     * @todo   Implement testDescribe().
     */
    public function testDescribe() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::tableExist
     * @todo   Implement testTableExist().
     */
    public function testTableExist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::getTableNumRows
     * @todo   Implement testGetTableNumRows().
     */
    public function testGetTableNumRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::createTable
     * @todo   Implement testCreateTable().
     */
    public function testCreateTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::truncateTable
     * @todo   Implement testTruncateTable().
     */
    public function testTruncateTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::addTableKey
     * @todo   Implement testAddTableKey().
     */
    public function testAddTableKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::createTableQuery
     * @todo   Implement testCreateTableQuery().
     */
    public function testCreateTableQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::listTables
     * @todo   Implement testListTables().
     */
    public function testListTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::createMissingColumns
     * @todo   Implement testCreateMissingColumns().
     */
    public function testCreateMissingColumns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::close
     * @todo   Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\MySqli::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
