<?php

namespace Test\Ease\SQL;

use Ease\SQL\PDO;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:19.
 */
class PDOTest extends SQLTest
{
    /**
     * @var PDO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new PDO();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers Ease\SQL\PDO::singleton
     *
     * @todo   Implement testSingleton().
     */
    public function testSingleton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::setKeyColumn
     *
     * @todo   Implement testSetKeyColumn().
     */
    public function testSetKeyColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::setTableName
     *
     * @todo   Implement testSetTableName().
     */
    public function testSetTableName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::addSlashes
     *
     * @todo   Implement testAddSlashes().
     */
    public function testAddSlashes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::connect
     *
     * @todo   Implement testConnect().
     */
    public function testConnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::selectDB
     *
     * @todo   Implement testSelectDB().
     */
    public function testSelectDB()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::exeQuery
     *
     * @todo   Implement testExeQuery().
     */
    public function testExeQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::getlastInsertID
     *
     * @todo   Implement testGetlastInsertID().
     */
    public function testGetlastInsertID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::queryToArray
     *
     * @todo   Implement testQueryToArray().
     */
    public function testQueryToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::arrayToInsert
     *
     * @todo   Implement testArrayToInsert().
     */
    public function testArrayToInsert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::arrayToUpdate
     *
     * @todo   Implement testArrayToUpdate().
     */
    public function testArrayToUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::arrayToQuery
     *
     * @todo   Implement testArrayToQuery().
     */
    public function testArrayToQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::arrayToInsertQuery
     *
     * @todo   Implement testArrayToInsertQuery().
     */
    public function testArrayToInsertQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::arrayToValuesQuery
     *
     * @todo   Implement testArrayToValuesQuery().
     */
    public function testArrayToValuesQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::arrayToSetQuery
     *
     * @todo   Implement testArrayToSetQuery().
     */
    public function testArrayToSetQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::prepSelect
     *
     * @todo   Implement testPrepSelect().
     */
    public function testPrepSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::getTableNumRows
     *
     * @todo   Implement testGetTableNumRows().
     */
    public function testGetTableNumRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::getColumnComma
     *
     * @todo   Implement testGetColumnComma().
     */
    public function testGetColumnComma()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::close
     *
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::__destruct
     *
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\SQL\PDO::__sleep
     *
     * @todo   Implement test__sleep().
     */
    public function test__sleep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
