<?php

namespace Test\Ease\TWB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:42.
 */
class ButtonDropdownTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ButtonDropdown
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ButtonDropdown;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ease\TWB\ButtonDropdown::addMenuItem
     * @todo   Implement testAddMenuItem().
     */
    public function testAddMenuItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\TWB\ButtonDropdown::divider
     * @todo   Implement testDivider().
     */
    public function testDivider() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
