<?php

namespace Test\Ease\TWB;

use \Ease\TWB\ButtonGroup;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-26 at 19:03:14.
 */
class ButtonGroupTest extends \Test\Ease\Html\DivTest
{
    /**
     * @var ButtonGroup
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ButtonGroup('testGroup');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Ease\TWB\ButtonGroup::addButton
     * @todo   Implement testAddButton().
     */
    public function testAddButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
