<?php

namespace Test\Ease\TWB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:47.
 */
class FormGroupTest extends \Test\Ease\Html\DivTagTest
{
    /**
     * @var FormGroup
     */
    protected $object;

    public $rendered = '<div class="form-group"><label for="Label">Label</label><input type="text" name="text" class="form-control" id="Label" /></div>';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\TWB\FormGroup('Label',
            new \Ease\Html\InputTextTag('text'));
    }

    public function testConstructor()
    {
        $classname = get_class($this->object);

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
            ->disableOriginalConstructor()
            ->getMockForAbstractClass();
        $mock->__construct('Label', new \Ease\Html\InputTextTag('text'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}
