<?php

namespace Test\Ease\TWB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:31.
 */
class NavbarTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Navbar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        $this->object = new \Ease\TWB\Navbar;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() 
    {
        
    }

    /**
     * @covers Ease\TWB\Navbar::NavBarHeader
     * @todo   Implement testNavBarHeader().
     */
    public function testNavBarHeader() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\TWB\Navbar::addItem
     * @todo   Implement testAddItem().
     */
    public function testAddItem() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\TWB\Navbar::addMenuItem
     * @todo   Implement testAddMenuItem().
     */
    public function testAddMenuItem() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\TWB\Navbar::addDropDownSubmenu
     * @todo   Implement testAddDropDownSubmenu().
     */
    public function testAddDropDownSubmenu() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\TWB\Navbar::addDropDownMenu
     * @todo   Implement testAddDropDownMenu().
     */
    public function testAddDropDownMenu() 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
