<?php

namespace Test\Ease\TWB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:49.
 */
class RadioButtonTest extends \Test\Ease\Html\DivTagTest
{
    /**
     * @var RadioButton
     */
    protected $object;

    public $rendered = '<div><label for="radio"><input name="radio" value="X" type="radio" />test</label></div>';


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\TWB\RadioButton('radio', 'X', 'test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

}
