<?php

namespace Test\Ease\TWB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:41.
 */
class StatusMessagesTest extends \Test\Ease\Html\DivTest
{

    /**
     * @var StatusMessages
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        $this->object = new \Ease\TWB\StatusMessages();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() 
    {
        
    }

    /**
     * @covers Ease\TWB\StatusMessages::draw
     * @todo   Implement testDraw().
     */
    public function testDraw($whatWant = null) 
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
