<?php

namespace Test\Ease\TWB;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:34.
 */
class WebPageTest extends \Test\Ease\WebPageTest
{
    /**
     * @var WebPage
     */
    protected $object;
    
    public $rendered = '<!DOCTYPE html><html lang="cs-CZ"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta name="viewport" content="width=device-width,initial-scale=1.0"><title></title><link href="/javascript/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css" media="screen" /><style></style>
<script>
// <![CDATA[
window.location = "login.php"
// ]]>
</script>

<script>
// <![CDATA[
window.location = "http://v.s.cz/"
// ]]>
</script>
</head><body></body></html>';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\TWB\WebPage();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers Ease\TWB\WebPage::getStatusMessagesAsHtml
     *
     * @todo   Implement testGetStatusMessagesAsHtml().
     */
    public function testGetStatusMessagesAsHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
