<?php

namespace Test\Ease\TWB4;

use \Ease\TWB4\Alert;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:35.
 */
class AlertTest extends \Test\Ease\Html\DivTagTest
{
    /**
     * @var Alert
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Ease\TWB4\Alert('success');
    }

    public function testConstructor()
    {
        $classname = get_class($this->object);

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
            ->disableOriginalConstructor()
            ->getMockForAbstractClass();
        $mock->__construct('warning');

        $mock->__construct('danger', 'content');
        $mock->__construct('PairTag', 'test', ['title' => 'Pokus', 'id' => 'testing']);
    }
    
    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
